name: hockey-pool
services:
  - name: hockey-pool
    github:
      repo: travisdrawn/hockeyPool
      branch: master
      deploy_on_push: true
    build_command: npm ci --omit=dev
    run_command: node server.js
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: ADMIN_KEY
        scope: RUN_TIME
        type: SECRET
      - key: PORT
        scope: RUN_TIME
        value: "8080"
      - key: BASE_PATH
        scope: RUN_TIME
        value: "/hockeypool"
